security:
  # ...

#  password_hashers:
#    # auto hasher with default options for the User class (and children)
#    App\Entity\User: 'auto'
#
#    # auto hasher with custom options for all PasswordAuthenticatedUserInterface instances
#    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
#      algorithm: 'auto'
#      cost:      15
  password_hashers:
    App\Entity\User: 'auto'
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
      algorithm: 'auto'
      cost: 15
  firewalls:
    main:
