services:

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - 81:80
    volumes:
      - .:/var/www/payment-project
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - symfony
    links:
      - symfony

  symfony:
    container_name: symfony
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /var/www/payment-project
    volumes:
      - .:/var/www/payment-project
    links:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: some-password
      MYSQL_DATABASE: payments-api
    volumes:
      - /var/lib/mysql
      - ./dump.sql:/var/lib/dump.sql
    ports:
      - '3316:3306'


